### ISSUE TITLE
About training process

### ISSUE THREAD

**Issue by ZhangHaoyi** [yasunorikudo/chainer-ResNet#2]
It seems that there is no training process in your code,only including forward prop and prediction.Did I miss something?

**Comment by yasunorikudo** [comment]
Sorry for  inconvenient.
This repository doesn't include training scripts.
If you want to train ResNet from scratch, see the chainer sample code that train CNN for ImageNet.(https://github.com/pfnet/chainer/tree/master/examples/imagenet)
You can use my ResNet definition scripts in that sample training code.

**Comment by ZhangHaoyi** [comment]
Thx for your reply! looking forward to your next post..

**Comment by santle** [comment]
I completed all instructions mentioned by you in the guidelines.
on executing: python predict.py --model ResNet152 --img cat.png
I am getting an error message:
Traceback (most recent call last):
  File "predict.py", line 32, in <module>
    pred = model(x_data,None).data
  File "/home/tyco-gpu/santle/chainer-ResNet-master/ResNet152.py", line 98, in __call__
    h = self.res2(h, self.train)
  File "/home/tyco-gpu/santle/chainer-ResNet-master/ResNet152.py", line 68, in __call__
    x = f(x)
TypeError: __call__() takes exactly 3 arguments (2 given)

Any direction to solve this issue?
Thanks in advance for your help.
