### ISSUE TITLE
Execution error 

### ISSUE THREAD

**Issue by santle** [yasunorikudo/chainer-ResNet#3]
I completed all instructions mentioned by you in the guidelines.
on executing:     python predict.py --model ResNet152 --img cat.png
I am getting an error message:
Traceback (most recent call last):
File "predict.py", line 32, in 
pred = model(x_data,None).data
File ".../chainer-ResNet-master/ResNet152.py", line 98, in call
h = self.res2(h, self.train)
File ".../chainer-ResNet-master/ResNet152.py", line 68, in call
x = f(x)
TypeError: call() takes exactly 3 arguments (2 given)

Any directions to solve this issue?
Thanks in advance for your help.

**Comment by yasunorikudo** [comment]
Sorry for inconvenient.
I fixed "predict.py".
https://github.com/yasunorikudo/chainer-ResNet/commit/891cc9a2befe13eb7466226e3dc0d23287c13e28
Plese fix the code or pull this repository again.

**Comment by santle** [comment]
It works for me. thanks.
